#!/bin/bash

PWD=`pwd`
cd src/dlbc/plugins

echo "// Written in the D programming language."
echo
echo "/**"
echo "   List of plugin modules that have parameters to be registered."
echo "   This file has been automatically generated by \$(D $0)."
echo
echo "   Copyright: Stefan Frijters 2011-2015"
echo
echo "   License: \$(HTTP www.gnu.org/licenses/gpl-3.0.txt, GNU General Public License, version 3 (GPL-3.0))."
echo
echo "   Authors: Stefan Frijters"
echo "*/"
echo
echo "module dlbc.plugins.plist;"
echo
echo "import std.typetuple; // For TypeTuple / AliasSeq - keep for now for backwards compatibility"
echo
echo "alias parameterSourcePluginModules = TypeTuple!("

for f in `find . -name "*.d" | sort`; do
    # Ignore ./plist.d, as we want to write to this.
    if [[ "$f" != "./plist.d" ]]; then
	grep -e '^@("param")' --quiet $f
	NOT_FOUND=$?
	if [[ "$NOT_FOUND" -eq 0 ]]; then
	    MNAME=`echo $f | sed -e 's/^\.\//dlbc.plugins./' -e 's/\.d$//' -e 's/\//./'`
	    echo "  \"$MNAME\","
	fi
    fi
done

echo ");"

cd $PWD

